sudo: false

language: php

matrix:
  fast_finish: true
  include:
    - php: 5.4
    - php: 5.5
    - php: 5.6
      env:
        - EXECUTE_COVERAGE=true
    - php: 7
    - php: hhvm
  allow_failures:
    - php: 7

notifications:
  email: false

before_install:
  - if [[ $EXECUTE_COVERAGE != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi

install:
  - composer install

script:
  - if [[ $EXECUTE_COVERAGE == 'true' ]]; then ./vendor/bin/phpunit --coverage-clover clover.xml ; fi
  - if [[ $EXECUTE_COVERAGE != 'true' ]]; then ./vendor/bin/phpunit ; fi

after_script:
  - if [[ $EXECUTE_COVERAGE == 'true' ]]; then ./vendor/bin/codacycoverage clover clover.xml ; fi
phpunit.xml.dist
